# Generated by Django 5.1.7 on 2025-03-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='lcaol',
            new_name='local',
        ),
    ]
