# Generated by Django 5.1.7 on 2025-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0004_alter_evento_capacidade_alter_evento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
