# Generated by Django 5.1.7 on 2025-03-28 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0006_alter_evento_capacidade_alter_evento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
