# Generated by Django 5.1.7 on 2025-03-28 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0007_alter_evento_capacidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
