# Generated by Django 5.1.7 on 2025-03-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0008_alter_participante_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
